### ISSUE TITLE
Getting error on undo-propose-diff and some other functions too

### ISSUE THREAD

**Issue by Compro-Prasad** [jackkamm/undo-propose-el#7]
Tested in spacemacs.

Backtrace:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  get-buffer(nil)
  ediff-buffers-internal(nil #<buffer *scratch*> nil nil ediff-buffers)
  ediff-buffers(nil #<buffer *scratch*>)
  undo-propose-diff()
  funcall-interactively(undo-propose-diff)
  call-interactively(undo-propose-diff nil nil)
  command-execute(undo-propose-diff)
```

**Comment by terlar** [comment]
I think this is due to scratch not being a file buffer

**Comment by jackkamm** [comment]
It looks like you are calling `undo-propose-diff` within the original `*scratch*` buffer, rather than within the new temporary buffer which should be named like `*Undo Propose: *scratch**`. Is this the case? `undo-propose-diff` should be called from within the new temporary buffer, not from the original buffer.

It's possible that you aren't getting sent to the undo-propose temporary buffer because you've configured spacemacs to fix the window-layout -- I'm vaguely aware that spacemacs can do this but not at all familiar with it, nor which packages that spacemacs uses to configure window layout.

Right now `undo-propose` calls `(switch-to-buffer tmp-buffer)` with the intention that the window of the current buffer will switch to the new tmp-buffer, but maybe there is a more robust way to do this.

I just tested undo-propose in vanilla spacemacs (develop branch), in the scratch buffer, and it worked fine for me.

**Comment by Compro-Prasad** [comment]
It also happened with `init.el`

**Comment by Compro-Prasad** [comment]
The window configuration might be the issue which is controlled by popwin package in spacemacs.

**Comment by jackkamm** [comment]
If you can post the relevant parts of your spacemacs/popwin config I'll try to reproduce it to solve this issue.

**Comment by Compro-Prasad** [comment]
I don't have any of my custom config. Its all from Spacemacs.

**Comment by jackkamm** [comment]
I've made a commit that attempts to force the tmp-buffer to be in the same window as the original buffer. Hopefully that should solve this issue. Unfortunately, since I am unable to reproduce this problem, I cannot test it. @Compro-Prasad if you can test this, or provide a minimal reproducible example, it would be much appreciated.

**Comment by Compro-Prasad** [comment]
Its fixed.
